/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BagRouteImport } from './routes/bag'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomDesignsRouteImport } from './routes/custom-designs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeasurementsRouteImport } from './routes/measurements'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BagRoute = BagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomDesignsRoute = CustomDesignsRouteImport.update({
  id: '/custom-designs',
  path: '/custom-designs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementsRoute = MeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-designs': typeof CustomDesignsRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/order-success': typeof OrderSuccessRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-designs': typeof CustomDesignsRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/order-success': typeof OrderSuccessRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-designs': typeof CustomDesignsRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/order-success': typeof OrderSuccessRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bag'
    | '/checkout'
    | '/contact'
    | '/custom-designs'
    | '/login'
    | '/measurements'
    | '/order-success'
    | '/privacy-policy'
    | '/profile'
    | '/refund-policy'
    | '/register'
    | '/shipping'
    | '/shop'
    | '/terms-of-service'
    | '/collections/$slug'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bag'
    | '/checkout'
    | '/contact'
    | '/custom-designs'
    | '/login'
    | '/measurements'
    | '/order-success'
    | '/privacy-policy'
    | '/profile'
    | '/refund-policy'
    | '/register'
    | '/shipping'
    | '/shop'
    | '/terms-of-service'
    | '/collections/$slug'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bag'
    | '/checkout'
    | '/contact'
    | '/custom-designs'
    | '/login'
    | '/measurements'
    | '/order-success'
    | '/privacy-policy'
    | '/profile'
    | '/refund-policy'
    | '/register'
    | '/shipping'
    | '/shop'
    | '/terms-of-service'
    | '/collections/$slug'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BagRoute: typeof BagRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CustomDesignsRoute: typeof CustomDesignsRoute
  LoginRoute: typeof LoginRoute
  MeasurementsRoute: typeof MeasurementsRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RegisterRoute: typeof RegisterRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag': {
      id: '/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof BagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-designs': {
      id: '/custom-designs'
      path: '/custom-designs'
      fullPath: '/custom-designs'
      preLoaderRoute: typeof CustomDesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurements': {
      id: '/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof MeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BagRoute: BagRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CustomDesignsRoute: CustomDesignsRoute,
  LoginRoute: LoginRoute,
  MeasurementsRoute: MeasurementsRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RegisterRoute: RegisterRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
